fileVersion: 1
id: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
name: IBINVALUES
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: SRC_SAP
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 63ddb845-af6b-42a9-8a7e-50edefe8d03a
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        name: MANDT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: feb66fbf-8b61-45b0-bbe7-b4d131d798dd
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: VARCHAR(22)
        defaultValue: ""
        description: ""
        name: IN_RECNO
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 962e4c1c-4d5a-41f5-ab8b-6286063accb4
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: IN_SEGMCNT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7350bbc5-e3bd-4e46-8fdb-96b80f8694a7
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: NUMBER(12,0)
        defaultValue: ""
        description: ""
        name: SYMBOL_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c0f58a7a-0e57-4aa9-bd80-5182cc83fadd
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: VARCHAR(1)
        defaultValue: ""
        description: ""
        name: ASSTYP
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 287ae53f-fa0e-48da-b2af-6410067e1a37
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: VARCHAR(1)
        defaultValue: ""
        description: ""
        name: ATAUT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 0576fb29-34f4-4c73-bf62-1b3746ec4501
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        name: MSEHI_LOW
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: bebec810-efa2-4421-b27e-26f604af91dd
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        name: MSEHI_HIGH
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 9a593701-480c-4502-8f79-f3876c1ba553
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: ATSRT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: bdfc5409-2a12-497a-bdc8-5a5a254338a7
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: ATZIS
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 12d2d7fd-7d5f-40ed-bf3f-d174c91ddeeb
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: NUMBER(10,0)
        defaultValue: ""
        description: ""
        name: ATIMB
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: a6efa93e-64b9-45d0-9220-90cf05371a5c
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: VARCHAR(1)
        defaultValue: ""
        description: ""
        name: ARCHIVE_FLAG$
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 4a288c80-52db-4efb-be2f-7eaf67ac6715
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: TIMESTAMP_NTZ(0)
        defaultValue: ""
        description: ""
        name: ARCHIVE_TIMESTAMP$
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 2f0588de-48e2-4f38-9b90-d36482816054
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: TIMESTAMP_NTZ(0)
        defaultValue: ""
        description: ""
        name: SOURCE_UPDATE_TS
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 77a0af8d-8124-4567-a6b8-92a2259fabfd
          stepCounter: b92ef7f2-9663-44a2-8903-e3b17ceaed5c
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        name: UPDATE_TS
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
  name: IBINVALUES
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
